Details page now displays real data
SoftuniTeamBeyond2022/Feel-The-Quake pull request #13
Opened 2023-05-26 20:14 UTC by Jordan-Dimitrov

2023-05-29 06:19 UTC, Kardam-Simeonov requested changes

2023-05-29 06:19 UTC, Kardam-Simeonov commented on feel-the-quake/src/views/QuakeDetailsView.vue
> +
Супер! Обаче в този случай се правят два GET request-а на startup. Веднъж тук и втория път при инициализирането на картата. Данните може да се извлекат директно от маркера на картата, без да се прави fetch.

2023-05-31 06:29 UTC, Jordan-Dimitrov commented on feel-the-quake/src/views/QuakeDetailsView.vue
> +
shefe ne znam kak

2023-05-31 06:29 UTC, Jordan-Dimitrov commented on feel-the-quake/src/views/QuakeDetailsView.vue
> +
Като ида в нас ще го оправя

2023-06-24 19:04 UTC, merged